# Generated by Django 5.0.1 on 2024-11-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_cartitem_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.product",
            ),
            preserve_default=False,
        ),
    ]
